### ISSUE TITLE
foundry-factory generator error

### ISSUE THREAD

**Issue by Turqueso** [ghost-fvtt/foundry-factory#40]
I just installed it and when using `foundry-factory` I get this error

```
.......\AppData\Roaming\nvm\v12.0.0\node_modules\@ghost-fvtt\foundry-factory\dist\index.mjs:2
import { Command, Option } from 'commander';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by ghost91-** [comment]
The issue was due to an old Node.js version (12.0.0). Updating to a recent v14 / v16 version fixed the problem.
